Base
KrystianEE/projekt pull request #2
Opened 2018-05-25 11:10 UTC by KrystianEE

2018-05-25 13:25 UTC, KrystianEE commented
Mam póki co problem z tym że zdjęcie nie chce się wyświetlić :/

2018-05-25 14:06 UTC, ludwiktrammer requested changes

2018-05-25 14:06 UTC, ludwiktrammer commented on .gitignore
> +*migrations*
Migracje powinny być w repo - one zapisują informacje o tym do zmieniłeś w modelach, których nie da się wyciągnąć z samego kodu. Dzięki nim inni użytkownicy aplikacji mogą odpowiednio dostosować bazy danych u siebie.

2018-05-25 14:06 UTC, ludwiktrammer commented on kupiekota/accounts/views.py
> +from django.contrib.auth import login, logout
Masz tu dużo importów których nie używasz. Gdy zainstalujesz `flake8` to powinien Ci przypominać o wywaleniu ich.

2018-05-25 14:06 UTC, ludwiktrammer commented on kupiekota/posts/templates/posts/post_list.html
> +    <img src="{{post.post_image.url}}" alt="Fuck.">
Znałem dużo programistów którzy używali przekleństw jako tekstów do testowania w prawdziwych projektach, ale staramy się tego nie robić, bo zawsze prędzej czy później coś zostanie i nagle trafi do klienta :)

2018-05-25 14:06 UTC, ludwiktrammer commented on kupiekota/kupiekota/urls.py
> +] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
Powinieneś też takie dodać dla `MEDIA_URL` i `MEDIA_ROOT` - wtedy obrazki przesyłane w Django admin będą ci się pokazywać.

2018-05-25 14:06 UTC, ludwiktrammer commented on .gitignore
> +*migrations*
Za to ignorowane powinny być też pliki w folderze media (ale nie folderze static) - to są rzeczy przesyłane przez użytkowników konkretnej instancji, a nie część samej aplikacji.

2018-05-25 14:07 UTC, ludwiktrammer commented
Dodatkowo masz konflikty - prawdopodobnie zrobiłeś ten commit na starym branchu (tym który został już wcześniej zmergowany) zamiast zrobić świeży branch.

2018-05-28 09:05 UTC, KrystianEE commented
Mam problem taki że po tym jak się wypełni ankietę o ogłoszeniu to jest błąd "NOT NULL constraint failed: posts_post.owner_id"

2018-05-28 12:55 UTC, ludwiktrammer requested changes

2018-05-28 12:55 UTC, ludwiktrammer commented on .gitignore
> +*media*
Pliki powinny kończyć się znakiem nowej linii, tu tego znaku brakuje.
Też ta reguła jest bardzo ogólna - wyklucza jakikolwiek plik gdziekolwiek w projekcie, który gdziekolwiek w nazwie ma "media" (więc np. `socialmedia.jpg` się nie doda do repo). Zrób zamiast tego `media/`.

2018-05-28 12:55 UTC, ludwiktrammer commented on .gitignore
> +*media*
Pliki powinny kończyć się znakiem nowej linii, tu tego znaku brakuje.
Też ta reguła jest bardzo ogólna - wyklucza jakikolwiek plik gdziekolwiek w projekcie, który gdziekolwiek w nazwie ma "media" (więc np. `socialmedia.jpg` się nie doda do repo). Zrób zamiast tego `media/`.

2018-05-28 12:55 UTC, ludwiktrammer commented on kupiekota/posts/views.py
> +        self.object.user = self.request.user
Z tego co widzę model `Post` nie ma pola `user`

2018-05-28 12:55 UTC, ludwiktrammer commented on kupiekota/templates/base.html
> +    <nav class="navbar navbar-expand-lg fixed-top navbar-light" style="background-color: #f29a15;">
Style zawsze powinny żyć w plikach css, nie wewnątrz tagów HTML. Chodzi o rozdzielenie struktury dokumentu (HTML) od jego wyglądu (CSS).

2018-05-29 12:12 UTC, closed without merging