Work in progress
KrystianEE/projekt pull request #4
Opened 2018-06-04 08:54 UTC by KrystianEE

2018-06-04 11:55 UTC, KrystianEE commented
Chyba koniec

2018-06-05 09:23 UTC, ludwiktrammer requested changes

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/models.py
> +class MsgBox(models.Model):
Nadal ten model wydaje mi się totalnie nadmiarowy, ale ok ;)

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/models.py
> +        return str(self.user1)+" + "+str(self.user2)
`return "{} {}".format(self.user1, self.user2)` jest preferowaną wersją.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/models.py
> +    send_at = models.DateTimeField(default=timezone.now)
Zamiast `default=timezone.now` możesz napisać `auto_now_add=True`. To pierwsze ma sens bardziej jak dajesz domyślną propozycję, ale użytkownik może z niej nie skorzystać i wpisać inną wartość, a drugie gdy to pole zawsze powinno zawierać autentyczną datę dodania.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/templates/usermsg/userbox_detail.html
> +    {% if usermsg.sender == cur_user %}
Nazwa zmiennej `cur_user` jest bardzo niejasna. W programowaniu unika się skrótowców, bo potem osoba która to czyta nie wie o co chodzi. Powinieneś móc napisać `usermsg.sender == request.user`, co nie wymaga dodawania żadnych dodatkowych rzeczy do kontekstu i będzie od razu zrozumiałe dla każdego programisty Django.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/templates/usermsg/userbox_detail.html
> +    <p id="contentmsg">{{ usermsg.content }}</p>
Przydałyby się wcięcia do rzeczy objętych if / else.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/templates/usermsg/userbox_detail.html
> +    {% if usermsg.sender == cur_user %}
Dodatkowo robisz if / else na cały duży blok, gdzie duplikujesz cały kod związany z wyświetlaniem wiadomości (a nie ma nic gorszego w programowaniu niż duplikacja kodu - bo potem do końca świata musisz pilnować żeby obie wersje były zsynchronizowane) tylko po to żeby dodać jedno `<strong>`.

Z tym wiąże się jeszcze jedna kwestia - definicje wyglądu powinny być zawsze w CSS. `<strong>` możesz użyć żeby oznaczyć fragment tekstu który _semantycznie_ ma większą wagę niż otaczający tekst (np. słowo na który powinien być postawiony akcent). Nigdy po prostu dlatego, że coś masz ochotę pogrubić.

W takiej sytuacji jak ta należy po prostu nadać blokowi odpowiednią klasę. Potem w CSS możesz zdecydować i w przyszłości dowolnie zmieniać to jak dana klasa ma wyglądać - czy ma być pogrubiona, czy mieć inny kolor tła, czy coś zupełnie innego. To zupełnie nie dotyczy HTMLa. Nie powinieneś musieć dotykać kodu skórki żeby zmienić to jak wizualnie odróżniasz wiadomości odebrane i wysłane.

Ten kod powinien wyglądać jakoś tam:

```
<div class="{% if usermsg.sender == requset.user %}msg-sender{% else %}msg-receiver{% endif %}">
    <p id="contentmsg">{{ usermsg.content }}</p>
    <p id='smaller-text'> {{ usermsg.sender.username }} o {{ usermsg.send_at}}</p>
</div>
```

i wtedy w CSS możesz zrobić coś w stylu

```
.msg-receiver .contentmsg {
    font-weight: bold;
}
```

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/templates/usermsg/userbox_list.html
> +  <h5>Twoje rozmowy :</h5>
Przed `:` nie robi się spacji.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/views.py
> +        context['cur_user'] = self.request.user
Nie musisz tego dodawać do kontekst. Kontekst sam z siebie już zawiera `request`.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/views.py
> +    box = models.MsgBox.objects.get_or_create(user1=cur_user, user2=user)
Nazywasz to `box`, ale tak naprawdę to krotka w której pierwsza rzeczy to Twój box, a druga wartość logiczna mówiąca czy nowy obiekt został stworzony czy już był. Więc nazwa `box` wprowadza w błąd, a potem jak robisz `box[0].pk` jest zupełnie niejasne o co chodzi - czym jest wartość `[0]` z obiektu? Bez dokłądnego dokładnego przeanalizowania kodu wcześniej jest to nie do zrozumienia.

Powinieneś przy zapisywaniu od razu rozpakować wartości:

`box, _ = models.MsgBox.objects.get_or_create(user1=cur_user, user2=user)`

Wtedy w zmiennej `box` będzie rzeczywiście obiekt box.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/views.py
> +    cur_user = request.user
Wydaje mi się, że używanie `request.user` bezpośrednio, bez przemianowywania go będzie dużo czytelniejsze dla każdego czytającego Twój kod. Czasem warto przemianować jeśli wyrażenie jest strasznie długie, ale wtedy nowa zmienna powinna mieć pełną nazwę (`current_user`, nie `cur_user`). W tym wypadku `request.user` jest krótkie i zrozumiałe same w sobie, więc myślę że najlepiej używać go bezpośrednio.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/views.py
> +        usr = request.user
A tu przemianowujesz to `request.user` jeszcze raz w tej samej metodzie... na jeszcze większy skrótowiec.

2018-06-05 09:23 UTC, ludwiktrammer commented on kupiekota/usermsg/views.py
> +    if cur_user != box.user1 and cur_user != box.user2:
Te linie powinny być chyba na początku, żeby uniemożliwić komuś dodawanie wiadomości do cudzego boksu. Tak jak jest teraz najpierw wykonujesz cały kod zapisujący nową wiadomość do boksu, a dopiero potem sprawdzasz czy osoba miała uprawnienia żeby to zrobić - gdy jest już za późno. Dodatkowo jeśli ktoś nie ma uprawnień to należy zwrócić odpowiedni kod HTTP przeznaczony do takich sytuacji (403). W Django możesz to zrobić przez:

```
from django.core.exceptions import PermissionDenied
...
raise PermissionDenied
```

2018-06-05 11:37 UTC, ludwiktrammer requested changes

2018-06-05 11:37 UTC, ludwiktrammer commented on kupiekota/usermsg/views.py
> +    box,  = models.MsgBox.objects.get_or_create(user1=request.user, user2=user)
Powinno być `box, _ = ...`. Ta konstrukcja oznacza że pierwszy element zapisujesz do zmiennej `box`, a drugi do zmiennej `_`. Nazwa `_` jest w Pythonie tradycyjnie nadawana zmiennym które nie zostaną wykorzystane.

2018-06-05 12:49 UTC, ludwiktrammer requested changes

2018-06-05 12:49 UTC, ludwiktrammer commented on kupiekota/templates/base.html
> +          <a class="nav-item nav-link" href="{% url 'usermsg:userboxlist' username=request.user.username %}">Wiadomości</a>
Nie widzę żebyś potem w tym widoku wykorzystywał to `username`. Ten aparametr jest rzeczywiście potrzebny?

2018-06-05 12:49 UTC, ludwiktrammer commented on kupiekota/templates/index.html
> +    urzytkownikom wysyłać wiadomości między sobą.
"użytkownikom"

2018-06-06 09:53 UTC, ludwiktrammer approved these changes

2018-06-06 10:10 UTC, merged